
service: tim-test

provider:
  name: aws
  runtime: nodejs6.10

functions:
  create:
    handler: api/user.create
    events: 
      - http: post user
  auth:
    handler: api/user.auth
    events:
      - http: post token

plugins:
  - serverless-offline
  - serverless-dynamodb-local